server_side/detection/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('alert/<uuid:pk>/', views.alert, name='alert'),
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('', views.home, name= 'home'),
    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="detection/password_reset.html"),
        name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="detection/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="detection/password_reset_form.html"), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="detection/password_reset_done.html"), 
        name="password_reset_complete"),
    path('alert/<uuid:pk>/',views.alert, name= 'alert'),
]

server_side/wd_ss/urls.py
"""from django.contrib import admin
from django.urls import path, include
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('detection.urls')),
    re_path('api', include(('alertupload_rest.urls', 'alertupload_rest'), namespace='api')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)"""

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
#from django.conf.urls import url
from django.urls import re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('detection.urls')),
    re_path(r'^api/', include(('alertupload_rest.urls', 'alertupload_rest'), namespace='api')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server_side/detection/models.py
import os
import uuid
from django.db import models

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

from django.contrib.auth.models import User

# Changes uploaded file name
def scramble_uploaded_filename(instance, filename):
    """
    Scramble / uglify the filename of the uploaded file, but keep the files extension (e.g., .jpg or .png)
    :param instance:
    :param filename:
    :return:
    """
    extension = filename.split(".")[-1]
    return "{}.{}".format(uuid.uuid4(), extension)

# Data model
class UploadAlert(models.Model):
    image = models.ImageField("Uploaded image", upload_to=scramble_uploaded_filename)
    user_ID = models.ForeignKey(Token, on_delete=models.CASCADE)
    alert_receiver = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True)

# Generate and save a token each time a user is saved in a database
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

server_side/detection/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

# User registration form
class CreateUserForm(UserCreationForm):

	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

	# Checks if the provided email exists
	def clean_email(self):
		if User.objects.filter(email=self.cleaned_data['email']).exists():
			raise forms.ValidationError("The given email is already registered.")
		return self.cleaned_data['email']

server_side/detection/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import CreateUserForm

from .filters import DetectionFilter

from .models import UploadAlert

from rest_framework.authtoken.models import Token

# Handles the registration page
def registerPage(request):

	if request.user.is_authenticated:
		return redirect('home')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was successfully created for ' + user)

				return redirect('login')

		context = {'form':form}
		return render(request, 'detection/register.html', context)

# Handles the login page
def loginPage(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user) 
				return redirect('home')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'detection/login.html', context)

# Handles the logout
def logoutUser(request):
	logout(request)
	return redirect('login')

# Handles the dashboard page
@login_required(login_url='login')
def home(request):

	token = Token.objects.get(user=request.user)

	uploadAlert = UploadAlert.objects.filter(user_ID = token)

	myFilter = DetectionFilter(request.GET, queryset=uploadAlert)
	uploadAlert = myFilter.qs 

	context = {'myFilter':myFilter, 'uploadAlert':uploadAlert}

	return render(request, 'detection/dashboard.html', context)

# Handles the alert page
def alert(request, pk):

	uploadAlert = UploadAlert.objects.filter(image = str(pk) + ".jpg")

	myFilter = DetectionFilter(request.GET, queryset=uploadAlert)
	uploadAlert = myFilter.qs 

	context = {'myFilter':myFilter, 'uploadAlert':uploadAlert}

	return render(request, 'detection/alert.html', context)

server_side/detection/templates/detection/alert.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Alert</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/alert.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/navbar.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">


</head>
<body>

	<nav class="navbar navbar-dark bg-dark justify-content-between">
		<a class="navbar-brand" href="{% url 'home' %}" style="margin-left: 45px;">Weapon Detection System</a>	  
	</nav>
	
<div class="limiter">
<div class="container-login100 p-t-15">
<div class="wrap-login100 p-l-40 p-r-40 p-t-25 p-b-15">

	<table class="table">
		<tr>
			<th scope="col" class="top-row">Detection</th>
		</tr>

		{% for alert in uploadAlert %}

		<tr>
			<td class="w-25"><img class="img-fluid" src='https://127.0.0.1:8001/static/images{{alert.image}}'/></td>
		</tr>
		{% endfor %}
	</table>

			<table class="table">
				<tr>
					<th scope="col" class="top-row">Location</th>
					<th scope="col" class="top-row">Alert was sent to</th>
					<th scope="col" class="top-row">Time</th>
				</tr>

				{% for alert in uploadAlert %}

				<tr>
					<td>{{alert.location}}</td>
					<td>{{alert.alert_receiver}}</td>
					<td>{{alert.date_created|date:"Y-m-d H:i:s"}}</td>
					
				</tr>
				{% endfor %}

			</table>
		
</div>
</div>
</div>

</body>

</html>

server_side/detection/templates/detection/dashboard.html
{%  extends 'detection/main.html' %}

{% block content %}

{% load static %}

{% load event_tags %}

<div class="limiter">
<div class="container-login100 p-b-0 p-t-0">
	<div class="wrap-login100 p-l-30 p-r-30 p-t-20 p-b-20">
		<div class="Search">
			<form method="get">
				<div class="row">

					<div class="col">
						<!-- Location Input -->
						<input class="form-control" type="text"  placeholder="Location"
						name="{{ myFilter.form.location.name }}"
						id="{{ myFilter.form.location.id_for_label }}"
						{% if myFilter.form.location.value != None %}value="{{ myFilter.form.location.value|stringformat:'s' }}"{% endif %}
						maxlength="{{ myFilter.form.location.field.max_length }}"
						{% if myFilter.form.location.field.required %}required{% endif %}>
					</div>

					<div class="col">
						<!-- Alert was sent to Input -->
						<input class="form-control" type="text"  placeholder="Alert was sent to"
						name="{{ myFilter.form.alert_receiver.name }}"
						id="{{ myFilter.form.alert_receiver.id_for_label }}"
						{% if myFilter.form.alert_receiver.value != None %}value="{{ myFilter.form.alert_receiver.value|stringformat:'s' }}"{% endif %}
						maxlength="{{ myFilter.form.alert_receiver.field.max_length }}"
						{% if myFilter.form.alert_receiver.field.required %}required{% endif %}>
					</div>

					<div class="col-2">
						<!-- Start Date Input -->
						<input class="form-control" type="text" id="date" placeholder="Start Date" autocomplete="off"
						name="{{ myFilter.form.start_date.name }}"
						id="{{ myFilter.form.start_date.id_for_label }}"
						{% if myFilter.form.start_date.value != None %}value="{{ myFilter.form.start_date.value|stringformat:'s' }}"{% endif %}
						maxlength="{{ myFilter.form.start_date.field.max_length }}"
						{% if myFilter.form.start_date.field.required %}required{% endif %}>
					</div>

					<div class="col-2">
						<!-- End Date Input Input -->
						<input class="form-control" type="text" id="date" placeholder="End Date" autocomplete="off"
						name="{{ myFilter.form.end_date.name }}"
						id="{{ myFilter.form.end_date.id_for_label }}"
						{% if myFilter.form.end_date.value != None %}value="{{ myFilter.form.end_date.value|stringformat:'s' }}"{% endif %}
						maxlength="{{ myFilter.form.end_date.field.max_length }}"
						{% if myFilter.form.end_date.field.required %}required{% endif %}>
					</div>

					<div class="col-1">
						<button class="btn btn-primary" type="submit">Search</button>
					</div>
				  </div>
			</form>
		</div>
		
</div>
</div>
</div>

   <script>
	jQuery(document).ready(function($){
	  var date_input=$('input[id="date"]');
	  var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
	  var options={
		format: 'yyyy-mm-dd',
		container: container,
		todayHighlight: true,
		autoclose: true,
	  };
	  date_input.datepicker(options);
	});
	</script>
	
<div class="limiter">
<div class="container-login100 p-t-0">
<div class="wrap-login100 p-l-40 p-r-40 p-t-25 p-b-15">
		
			<table class="table table-image">
				<tr>
					<th scope="col" class="top-row">Detection</th>
					<th scope="col" class="top-row">Location</th>
					<th scope="col" class="top-row">Alert was sent to</th>
					<th scope="col" class="top-row">Time</th>
					<th scope="col" class="top-row">Alert</th>
				</tr>

				{% for alert in uploadAlert %}

				<tr>
					<td class="w-25"><img style="max-width: 250px; max-height: 150x; border-radius: 2.5%;" 
						class="img-fluid" src='https://n127.0.0.1:8001/static/images/{{alert.image}}'/></td>
					<td>{{alert.location}}</td>
					<td>{{alert.alert_receiver}}</td>
					<td>{{alert.date_created|date:"Y-m-d H:i:s"}}</td>
					
					{% with uuid=alert.image|split:"." %}

					<td><a class="btn btn-sm btn-info" href="/alert/{{uuid.0}}">View</a></td>

					{% endwith %}
					
				</tr>
				{% endfor %}

			</table>
		
</div>
</div>
</div>

{% endblock %}

server_side/detection/templates/detection/login.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">


</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" method="POST" action="">
					{% csrf_token %}
					<span class="login100-form-title p-b-33">
						Account Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="username" placeholder="Username">
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
					</div>

					<div class="container-login100-form-btn m-t-20 m-b-15">
						<button class="login100-form-btn" type="submit" value="Login">
							Sign in
						</button>
					</div>

					{% for message in messages %}
					<p id="messages">{{message}}</p>
					{% endfor %}	

					<div class="text-center p-t-15 p-b-4">
						<span class="txt1">
							Forgot
						</span>

						<a href="{% url 'reset_password' %}" class="txt2 hov1">
							Password?
						</a>
					</div>

					<div class="text-center">
						<span class="txt1">
							Create an account?
						</span>

						<a href="{% url 'register' %}" class="txt2 hov1">
							Sign up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

</body>

</html>

server_side/detection/templates/detection/main.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Weapon Detection System</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">

	<!--  jQuery -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

	<!-- Bootstrap Date-Picker Plugin -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>

</head>
<body>
	{%  include 'detection/navbar.html' %}
	<div class="container-fluid">

	{% block content %}

	{% endblock %}
    </div>
	
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

server_side/detection/templates/detection/navbar.html
  
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/css/navbar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">

<nav class="navbar navbar-dark bg-dark justify-content-between">
    <span class="navbar-brand" style="margin-left: 45px;">Weapon Detection System</span>

    <ul class="form-inline my-2 my-lg-0">
      <span class="hello-msg">Hello, {{request.user}}!</span>
      <span ><a class="hello-msg" href="{% url 'logout' %}">Logout</a></span>
    </ul>

  
  </nav>

server_side/detection/templates/detection/password_reset.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Reset Password</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">


</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" method="POST" action="">
					{% csrf_token %}
					<span class="login100-form-title p-b-20">
						Password Reset
					</span>

					<div class="text-center p-b-4">
						<p style="color: #555555;">
							Forgotten your password?
						</p>
						<p class="p-t-15 p-b-25">
							Enter your email address below, and we’ll email instructions for setting a new one.
						</p>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="email" name="email" autocomplete="email" placeholder="Email" id="id_email">
					</div>

					<div class="container-login100-form-btn m-t-20 m-b-15">
						<button class="login100-form-btn" type="submit" value="Send email">
							Submit
						</button>
					</div>
						
					<div class="text-center p-t-15">
						<span class="txt1">
							Remember your password?
						</span>

						<a href="{% url 'login' %}" class="txt2 hov1">
							Login
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

</body>

</html>

server_side/detection/templates/detection/password_reset_done.html
  
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Password Changed</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">


</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">

					<span class="login100-form-title p-b-15">
						Password Reset Complete
					</span>

					<div class="text-center p-b-4">

						<p class="p-b-4">
							Your password has been set.
						</p>
						<p>
							You may go ahead and 
							<a href="{% url 'login' %}" class="txt2 hov1">
								Login
							</a>
							now.
						</p>

					</div>
			</div>
		</div>
	</div>

</body>

</html>

server_side/detection/templates/detection/password_reset_form.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Reset Password</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">


</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" method="POST" action="">
					{% csrf_token %}
					<span class="login100-form-title p-b-20">
						Enter New Password
					</span>

					<div class="text-center p-b-15">
						<p>Please enter your new password twice so we can verify you typed it in correctly.</p>
					</div>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1" aria-autocomplete="list" placeholder="Password">
					</div>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2" placeholder="Repeat password">
					</div>

					<div class="container-login100-form-btn m-t-20 m-b-15">
						<button class="login100-form-btn" type="submit" value="Update Password">
							Submit
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>

</body>

</html>

server_side/detection/templates/detection/password_reset_sent.html
  
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Password Reset sent</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">


</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">

					<span class="login100-form-title p-b-20">
						Password Reset Sent
					</span>

					<div class="text-center p-b-4">
						<p>
							We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
						</p>
						<p class="p-t-15 p-b-25">
							If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
						</p>
					</div>
						
			</div>
		</div>
	</div>

</body>

</html>

server_side/detection/templates/detection/register.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/register.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/util.css' %}">

</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" method="POST" action="">
					{% csrf_token %}
					<span class="login100-form-title p-b-33">
						Register Account
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="username" placeholder="Username">
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input class="input100" type="email" name="email" placeholder="Email">
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input class="input100" type="password" name="password1" placeholder="Password">
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input class="input100" type="password" name="password2" placeholder="Confirm Password">
					</div>

					<div class="container-login100-form-btn m-t-20 m-b-15">
						<button class="login100-form-btn" type="submit" value="Register">
							Create Account
						</button>
					</div>

					{% if form.errors %}
						{% for field in form %}				
							{% for error in field.errors %}
							<div class="error">
								<p class="field_label">{{field.label}}:</p>
								<p>{{ error|escape }}</p>
							</div>
							{% endfor %}
						{% endfor %}
					{% endif %}

					

					<div class="text-center p-t-15 p-b-4">
						<span class="txt1">
							Already have an account?
						</span>

						<a href="{% url 'login' %}" class="txt2 hov1">
							Login
						</a>
					</div>

				</form>
			</div>
		</div>
	</div>

</body>

</html>